### ISSUE TITLE
Apostrophe s handling 

### ISSUE THREAD

**Issue by lindsay-greene** [unccard/shiny-woRdcomplex-2.1#16]
Look for ’s in the input
Find info in database for characters in the word before the ’s (call that S) 
If the last letter of S is a voiceless consonant, add a s to the end of the Klattese - else add a z to the end 
Then continue to calculate as normal

**Comment by jaxtastic** [comment]
and for 'd, same rule, but add t if prior segment is voiceless else d. 
and for 've, add v
and for 'll, add syllabic L

**Comment by lindsay-greene** [comment]
this is currently working in this repo! i'm a little unsure how to update the server we published, but i'm looking into it. it might have to be done with the unccard email but i'm not sure yet
