### ISSUE TITLE
Display NA for words not found in DB 

### ISSUE THREAD

**Issue by lindsay-greene** [unccard/shiny-woRdcomplex-2.1#8]
optionally, display NA if words are not found in DB 

- use ```if(length(row) == 0)``` in ```retrieveDBInfo()``` for this conditional, return -1 if NA 
- display in database as NA and skip calculations for wbw and average
- use counter variable for # words found in db and use this instead of ```nrow(vals$word_by_word)``` in ```updateAverage```

**Comment by jaxtastic** [comment]
yes I think we should display NA for words not found, but skip calculations for these.

**Comment by jaxtastic** [comment]
Consider allowing user to specify Klattese transcriptions for words not in the dB? This could be another small table, with input as orthographic,Klattese

**Comment by lindsay-greene** [comment]
@jaxtastic if the user inputs a word that is in the database, and also specifies a klattese transcription in that new input box, what is the expected behavior? it might make sense to prioritize the input because they might have specific modifications they want, but it also might make sense to go off of the database which has word frequency information

**Comment by lindsay-greene** [comment]
done! it has the behavior outlined in the above comment
